//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DOPSEntities : DbContext
    {
        public DOPSEntities()
            : base("name=DOPSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Table_Account> Table_Account { get; set; }
        public virtual DbSet<Table_AlarmTriggers> Table_AlarmTriggers { get; set; }
        public virtual DbSet<Table_Clients> Table_Clients { get; set; }
        public virtual DbSet<Table_EmployeeAssignments> Table_EmployeeAssignments { get; set; }
        public virtual DbSet<Table_Employees> Table_Employees { get; set; }
        public virtual DbSet<Table_IMGRoomPlan> Table_IMGRoomPlan { get; set; }
        public virtual DbSet<Table_InspectionActs> Table_InspectionActs { get; set; }
        public virtual DbSet<Table_Position> Table_Position { get; set; }
        public virtual DbSet<Table_ResponsiblePersons> Table_ResponsiblePersons { get; set; }
        public virtual DbSet<Table_SecurityContracts> Table_SecurityContracts { get; set; }
        public virtual DbSet<Table_SecurityObjects> Table_SecurityObjects { get; set; }
        public virtual DbSet<Table_Sensors> Table_Sensors { get; set; }
        public virtual DbSet<Table_SensorsType> Table_SensorsType { get; set; }
    }
}
