//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Sensors
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_Sensors()
        {
            this.Table_AlarmTriggers = new HashSet<Table_AlarmTriggers>();
        }
    
        public int ID_Sensors { get; set; }
        public int ID_SecurityObjects { get; set; }
        public int ID_SensorsType { get; set; }
        public string Status { get; set; }
        public System.DateTime InstallationDate { get; set; }
        public System.DateTime LastMaintenance { get; set; }
        public bool IsFunctional { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_AlarmTriggers> Table_AlarmTriggers { get; set; }
        public virtual Table_SecurityObjects Table_SecurityObjects { get; set; }
        public virtual Table_SensorsType Table_SensorsType { get; set; }
    }
}
