//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_SecurityObjects
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_SecurityObjects()
        {
            this.Table_InspectionActs = new HashSet<Table_InspectionActs>();
            this.Table_SecurityContracts = new HashSet<Table_SecurityContracts>();
            this.Table_Sensors = new HashSet<Table_Sensors>();
        }
    
        public int ID_SecurityObjects { get; set; }
        public int ID_Clients { get; set; }
        public string Address { get; set; }
        public string Description { get; set; }
        public int ID_IMG_Room_Plan { get; set; }
        public string ResponsiblePersons { get; set; }
    
        public virtual Table_Clients Table_Clients { get; set; }
        public virtual Table_IMGRoomPlan Table_IMGRoomPlan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_InspectionActs> Table_InspectionActs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_SecurityContracts> Table_SecurityContracts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Sensors> Table_Sensors { get; set; }
    }
}
