//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Employees
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_Employees()
        {
            this.Table_EmployeeAssignments = new HashSet<Table_EmployeeAssignments>();
            this.Table_InspectionActs = new HashSet<Table_InspectionActs>();
            this.Table_SecurityContracts = new HashSet<Table_SecurityContracts>();
        }
    
        public int ID_Employees { get; set; }
        public int ID_Position { get; set; }
        public string Name { get; set; }
        public string ContactInfo { get; set; }
        public System.DateTime HireDate { get; set; }
        public bool Isonduty { get; set; }
        public int PatrolledObjectsCount { get; set; }
        public Nullable<int> ID_Account { get; set; }
        public string WorkAddress { get; set; }
        public Nullable<int> ProbationPeriod { get; set; }
        public string ContractNumber { get; set; }
        public string PassportData { get; set; }
        public string INN { get; set; }
        public string SNILS { get; set; }
        public Nullable<bool> TaxExemption { get; set; }
        public string AdditionalTerms { get; set; }
    
        public virtual Table_Account Table_Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_EmployeeAssignments> Table_EmployeeAssignments { get; set; }
        public virtual Table_Position Table_Position { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_InspectionActs> Table_InspectionActs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_SecurityContracts> Table_SecurityContracts { get; set; }
    }
}
