//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_EmployeeAssignments
    {
        public int ID_EmployeeAssignments { get; set; }
        public int ID_Employees { get; set; }
        public int ID_AlarmTriggers { get; set; }
        public string Taskstatus { get; set; }
        public string Feedback { get; set; }
        public bool IsResolved { get; set; }
    
        public virtual Table_AlarmTriggers Table_AlarmTriggers { get; set; }
        public virtual Table_Employees Table_Employees { get; set; }
    }
}
