//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_SecurityContracts
    {
        public int ID_SecurityContracts { get; set; }
        public int ID_SecurityObjects { get; set; }
        public int ID_Clients { get; set; }
        public int ID_Responsible_Employee { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Terms { get; set; }
        public string Contractstatus { get; set; }
        public decimal fee { get; set; }
    
        public virtual Table_Clients Table_Clients { get; set; }
        public virtual Table_Employees Table_Employees { get; set; }
        public virtual Table_SecurityObjects Table_SecurityObjects { get; set; }
    }
}
