//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_AlarmTriggers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_AlarmTriggers()
        {
            this.Table_EmployeeAssignments = new HashSet<Table_EmployeeAssignments>();
            this.Table_InspectionActs = new HashSet<Table_InspectionActs>();
        }
    
        public int ID_AlarmTriggers { get; set; }
        public Nullable<int> ID_InspectionActs { get; set; }
        public int ID_Sensors { get; set; }
        public System.DateTime Timestamp { get; set; }
        public bool IsFalsealarm { get; set; }
        public System.DateTime Responsetime { get; set; }
        public System.DateTime PatrolArrivalTime { get; set; }
    
        public virtual Table_Sensors Table_Sensors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_EmployeeAssignments> Table_EmployeeAssignments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_InspectionActs> Table_InspectionActs { get; set; }
    }
}
